Add Todo-app Project
KazanExpress/frontend-test-task pull request #1
Opened 2020-03-22 08:20 UTC by AntonBrock

**Список выполненых требованний:**
- Каждая новая вкладка с приложением - отдельный проект со своим списком задач;
- Редактируемое название проекта в качестве заголовка страницы;
- Список с задачами:
     - Добавление новой задачи в список;
     - Удаление любой задачи из списка;
     - Возможность пометить любую задачу сделанной и возможность убрать эту пометку (mark as done/not done);
- Вся информация (название проекта, список задач, состояние задач) должна сохраняться при перезагрузке страницы;
-  Поле ввода для поиска/фильтрации задач в списке (фильтр должен сохраняться после перезагрузки страницы);
- Возможность редактирования названия задачи после её создания;

**Инструкция по запуску**
### Project setup
`npm install`
### Compiles and hot-reloads for development
`npm serve`
### Compiles and minifies for production
`npm build`
### Lints and fixes files
`npm run lint`

2020-03-23 00:05 UTC, Raiondesu commented
Здравствуй, Антон! Благодарим за подготовку своего решения задачи. :)

Планируешь ли ты дополнять этот PR, или это окончательный вариант?

2020-03-23 13:38 UTC, AntonBrock commented
Добрый день, это окончательный вариант моего решения :)

2020-03-24 06:44 UTC, Raiondesu commented
К сожалению, для текущей вакансии, мы рассматриваем уровень выполнения задачи от medium и выше.

2020-03-24 06:48 UTC, Raiondesu requested changes
Для текущей вакансии мы рассматриваем уровень выполнения задачи от [medium](https://github.com/KazanExpress/frontend-test-task#medium) и выше.

Текущий PR содержит решение сложности [easy](https://github.com/KazanExpress/frontend-test-task#easy).

2020-03-24 06:58 UTC, AntonBrock commented
> Для текущей вакансии мы рассматриваем уровень выполнения задачи от [medium](https://github.com/KazanExpress/frontend-test-task#medium) и выше.
> 
> 
> 
> Текущий PR содержит решение сложности [easy](https://github.com/KazanExpress/frontend-test-task#easy).

Понял, спасибо

2020-03-29 23:19 UTC, closed without merging